name: DB CI (Supabase verify)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  verify-migrations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Supabase init
        run: supabase init
      - name: Start local DB & apply migrations
        run: supabase db start
      - name: Lint database schema
        run: supabase db lint --level error
      # - name: Run DB tests (pgTAP)
      #   run: supabase test db
